# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Docker birthday"
email: 
description: > # this means to ignore newlines until "baseurl:"
  Docker birthday
  
baseurl: # the subpath of your site, e.g. /blog
url: "https://birthday.play-with-docker.com" # the base hostname & protocol for your site

#sidebar
default-image: docker-logo.svg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: Docker Inc.
copyright:
   name: Docker, Inc.
   link: 'https://docker.com'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/
toc:
  min_level: 1
  max_level: 2

# Tracker
analytics: UA-89019737-3


#social
facebook: https://www.facebook.com/docker.run
twitter: https://twitter.com/docker
github: https://www.github.com/play-with-docker/play-with-docker.github.io
twitter_username: docker
youtube: https://youtube.com/docker.run

#facebook like box
fb-app-id: 549480635219583
fb-page-url: https://www.facebook.com/docker.run/
fb-page-title: Docker

# Sass style
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-toc]

# Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-toc

  
# Play with Docker
pwdurl: https://labs.play-with-docker.com
badge_api_url: https://birthday.lach.dev
